TMP - comment out Streamlit-specific things

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -203,45 +203,45 @@ commands:
 workflows:
   circleci:
     jobs:
-      - python-min-version: # Oldest supported Python minor version.
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/ # 0.56.1.dev20201129
-      - python-max-version: # Latest supported Python minor version.
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/
-      - cypress: # Non flaky Cypress tests
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/
-      - pr-preview: # Make a preview branch for each PR
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/
-      - nightly-release:
-          requires:
-            - python-min-version
-            - python-max-version
-            - cypress
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/
-            branches:
-              ignore: /.*/
+      # - python-min-version: # Oldest supported Python minor version.
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/ # 0.56.1.dev20201129
+      # - python-max-version: # Latest supported Python minor version.
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/
+      # - cypress: # Non flaky Cypress tests
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/
+      # - pr-preview: # Make a preview branch for each PR
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/
+      # - nightly-release:
+      #     requires:
+      #       - python-min-version
+      #       - python-max-version
+      #       - cypress
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/
+      #       branches:
+      #         ignore: /.*/
       - build-deploy-rc:
-          requires:
-            - python-min-version
-            - python-max-version
-            - cypress
+          # requires:
+          #   - python-min-version
+          #   - python-max-version
+          #   - cypress
           filters:
             branches:
               only: /^release\/([0-9]+\.){2}([0-9]+)/
       - build-deploy-release:
-          requires:
-            - python-min-version
-            - python-max-version
-            - cypress
+          # requires:
+          #   - python-min-version
+          #   - python-max-version
+          #   - cypress
           filters:
             tags:
               only: /^([0-9]+\.){2}([0-9]+)/
@@ -296,22 +296,26 @@ jobs:
             python scripts/update_version.py $STREAMLIT_RELEASE_SEMVER
 
       - run:
-          name: Commit version updates
-          command: |
-            git config user.email "core+streamlitbot-github@streamlit.io"
-            git config user.name "Streamlit Bot"
+          name: Output STREAMLIT_RELEASE_VERSION
+          command: echo -e "$STREAMLIT_RELEASE_VERSION"
 
-            git commit -am "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]" && git push origin $CIRCLE_BRANCH || echo "No changes to commit"
+      # - run:
+      #     name: Commit version updates
+      #     command: |
+      #       git config user.email "core+streamlitbot-github@streamlit.io"
+      #       git config user.name "Streamlit Bot"
 
-      # Password added to circleci environment
-      # https://ui.circleci.com/settings/project/github/streamlit/streamlit/environment-variables
-      - run:
-          name: init .pypirc
-          command: |
-            cd lib
-            echo -e "[pypi]" >> ~/.pypirc
-            echo -e "username = streamlit" >> ~/.pypirc
-            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
+      #       git commit -am "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]" && git push origin $CIRCLE_BRANCH || echo "No changes to commit"
+
+      # # Password added to circleci environment
+      # # https://ui.circleci.com/settings/project/github/streamlit/streamlit/environment-variables
+      # - run:
+      #     name: init .pypirc
+      #     command: |
+      #       cd lib
+      #       echo -e "[pypi]" >> ~/.pypirc
+      #       echo -e "username = streamlit" >> ~/.pypirc
+      #       echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
 
       - run:
           name: Make package
@@ -329,14 +333,14 @@ jobs:
       - store_artifacts:
           path: ./lib/dist
 
-      - run:
-          name: upload to pypi
-          command: |
-            make distribute
+      # - run:
+      #     name: upload to pypi
+      #     command: |
+      #       make distribute
 
-      - slack/status:
-          success_message: ":rocket: RC version ${STREAMLIT_RELEASE_SEMVER} was successful!"
-          failure_message: ":blobonfire: RC version ${STREAMLIT_RELEASE_SEMVER} failed to release"
+      # - slack/status:
+      #     success_message: ":rocket: RC version ${STREAMLIT_RELEASE_SEMVER} was successful!"
+      #     failure_message: ":blobonfire: RC version ${STREAMLIT_RELEASE_SEMVER} failed to release"
 
   build-deploy-release:
     resource_class: large
@@ -358,22 +362,26 @@ jobs:
           command: python scripts/update_version.py $STREAMLIT_RELEASE_VERSION
 
       - run:
-          name: Commit version updates
-          command: |
-            git config user.email "core+streamlitbot-github@streamlit.io"
-            git config user.name "Streamlit Bot"
+          name: Output STREAMLIT_RELEASE_VERSION
+          command: echo -e "$STREAMLIT_RELEASE_VERSION"
 
-            git commit -am "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]" && git push origin release/$CIRCLE_TAG || echo "No changes to commit"
+      # - run:
+      #     name: Commit version updates
+      #     command: |
+      #       git config user.email "core+streamlitbot-github@streamlit.io"
+      #       git config user.name "Streamlit Bot"
 
-      # Password added to circleci environment
-      # https://ui.circleci.com/settings/project/github/streamlit/streamlit/environment-variables
-      - run:
-          name: init .pypirc
-          command: |
-            cd lib
-            echo -e "[pypi]" >> ~/.pypirc
-            echo -e "username = streamlit" >> ~/.pypirc
-            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
+      #       git commit -am "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]" && git push origin release/$CIRCLE_TAG || echo "No changes to commit"
+
+      # # Password added to circleci environment
+      # # https://ui.circleci.com/settings/project/github/streamlit/streamlit/environment-variables
+      # - run:
+      #     name: init .pypirc
+      #     command: |
+      #       cd lib
+      #       echo -e "[pypi]" >> ~/.pypirc
+      #       echo -e "username = streamlit" >> ~/.pypirc
+      #       echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
 
       - run:
           name: Make package
@@ -391,10 +399,10 @@ jobs:
       - store_artifacts:
           path: ./lib/dist
 
-      - run:
-          name: upload to pypi
-          command: |
-            make distribute
+      # - run:
+      #     name: upload to pypi
+      #     command: |
+      #       make distribute
 
       - run:
           name: Mark GH release as official, upload artifacts
@@ -406,9 +414,9 @@ jobs:
           command: |
             echo "TODO: Merging branch..."
 
-      - slack/status:
-          success_message: ":rocket: RC version ${STREAMLIT_RELEASE_SEMVER} was successful!"
-          failure_message: ":blobonfire: RC version ${STREAMLIT_RELEASE_SEMVER} failed to release"
+      # - slack/status:
+      #     success_message: ":rocket: Version ${STREAMLIT_RELEASE_SEMVER} was successful!"
+      #     failure_message: ":blobonfire: Version ${STREAMLIT_RELEASE_SEMVER} failed to release"
 
   python-max-version: &job-template
     docker:
