[STLT-23] 🔄 (CircleCI Release Pipeline) Add pipeline to build and release

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -237,6 +237,16 @@ workflows:
           filters:
             branches:
               only: /^release\/([0-9]+\.){2}([0-9]+)/
+      - build-deploy-release:
+          requires:
+            - python-min-version
+            - python-max-version
+            - cypress
+          filters:
+            tags:
+              only: /^([0-9]+\.){2}([0-9]+)/
+            branches:
+              ignore: /.*/
 
       # Uncomment to get a button that runs flaky tests on CircleCI:
       # - cypress-flaky-approval:
@@ -328,6 +338,97 @@ jobs:
       - slack/status:
           success_message: ":rocket: RC version ${STREAMLIT_RELEASE_VERSION} was successful!"
           failure_message: ":blobonfire: RC version ${STREAMLIT_RELEASE_VERSION} failed to release"
+
+  build-deploy-release:
+    resource_class: large
+    docker:
+      - image: circleci/python:3.9.7
+    working_directory: ~/repo
+    steps:
+      - checkout:
+          name: Checkout Streamlit code
+
+      - configure-build-env
+
+      # TODO: we need to look up the info from GH, as the branch is not available when pushing a tag
+      # - run:
+      #     name: Ensure that version tag matches branch version
+      #     command: |
+      #       if [ "$(echo $CIRCLE_BRANCH | tr -d "release/")" != "$CIRCLE_TAG" ]
+      #       then
+      #         echo "ERROR: Version number from tag does not match the version number from the branch name."
+      #         exit 1
+      #       fi
+      - run:
+          name: Set desired version from branch name
+          command: echo 'export STREAMLIT_RELEASE_VERSION=$(echo $CIRCLE_BRANCH | tr -d "release/")' >> $BASH_ENV
+      - run:
+          name: Update streamlit version
+          command: |
+            echo "Release version ${STREAMLIT_RELEASE_VERSION}"
+            python scripts/update_version.py $STREAMLIT_RELEASE_VERSION
+      - run:
+          name: Commit version updates
+          command: |
+            git config user.email "core+streamlitbot-github@streamlit.io"
+            git config user.name "Streamlit Bot"
+
+            git commit -am "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]" && git push origin $CIRCLE_BRANCH || echo "No changes to commit"
+      - run:
+          name: Ensure that version tag matches the build version
+          command: |
+            cd lib
+            python setup.py verify
+
+      # Password added to circleci environment
+      # https://ui.circleci.com/settings/project/github/streamlit/streamlit/environment-variables
+      - run:
+          name: init .pypirc
+          command: |
+            cd lib
+            echo -e "[pypi]" >> ~/.pypirc
+            echo -e "username = streamlit" >> ~/.pypirc
+            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
+
+      - run:
+          name: Make package
+          no_output_timeout: 2h
+          command: |
+            echo "working directory = $(pwd)"
+            chmod +x ./frontend/scripts/preload-bokeh.sh
+            ${SUDO} apt-get install rsync
+            make package
+
+      # TODO: need to fix this - it doesn't seem to run with the correct build/version
+      # - run:
+      #     name: Run CLI regression tests with full build
+      #     command: |
+      #       make cli-regression-tests
+
+      - store_artifacts:
+          path: ./lib/dist
+
+      - run:
+          name: upload to pypi
+          command: |
+            make distribute
+
+      # TODO: do the thing
+      # - run:
+      #     name: Mark GH release as official, upload artifacts
+      #     command: |
+      #       echo "TODO: Updating GH release..."
+
+      # TODO: do the thing
+      # - run:
+      #     name: Merge branch
+      #     command: |
+      #       echo "TODO: Merging branch..."
+
+      # TODO: re-enable when not WIP
+      # - slack/status:
+      #     success_message: ":rocket: release version ${STREAMLIT_RELEASE_VERSION} was successful!"
+      #     failure_message: ":blobonfire: release version ${STREAMLIT_RELEASE_VERSION} failed to release"
 
   python-max-version: &job-template
     docker:
