TMP - comment out things to test GH flow

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -203,45 +203,45 @@ commands:
 workflows:
   circleci:
     jobs:
-      - python-min-version: # Oldest supported Python minor version.
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/ # 0.56.1.dev20201129
-      - python-max-version: # Latest supported Python minor version.
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/
-      - cypress: # Non flaky Cypress tests
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/
-      - pr-preview: # Make a preview branch for each PR
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/
-      - nightly-release:
-          requires:
-            - python-min-version
-            - python-max-version
-            - cypress
-          filters:
-            tags:
-              only: /^([0-9]+\.){3}dev[0-9]+/
-            branches:
-              ignore: /.*/
-      - build-deploy-rc:
-          requires:
-            - python-min-version
-            - python-max-version
-            - cypress
-          filters:
-            branches:
-              only: /^release\/([0-9]+\.){2}([0-9]+)/
+      # - python-min-version: # Oldest supported Python minor version.
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/ # 0.56.1.dev20201129
+      # - python-max-version: # Latest supported Python minor version.
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/
+      # - cypress: # Non flaky Cypress tests
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/
+      # - pr-preview: # Make a preview branch for each PR
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/
+      # - nightly-release:
+      #     requires:
+      #       - python-min-version
+      #       - python-max-version
+      #       - cypress
+      #     filters:
+      #       tags:
+      #         only: /^([0-9]+\.){3}dev[0-9]+/
+      #       branches:
+      #         ignore: /.*/
+      # - build-deploy-rc:
+      #     requires:
+      #       - python-min-version
+      #       - python-max-version
+      #       - cypress
+      #     filters:
+      #       branches:
+      #         only: /^release\/([0-9]+\.){2}([0-9]+)/
       - build-deploy-release:
-          requires:
-            - python-min-version
-            - python-max-version
-            - cypress
+          # requires:
+          #   - python-min-version
+          #   - python-max-version
+          #   - cypress
           filters:
             tags:
               only: /^([0-9]+\.){2}([0-9]+)/
@@ -386,22 +386,26 @@ jobs:
           command: python scripts/update_version.py $STREAMLIT_RELEASE_VERSION
 
       - run:
-          name: Commit version updates
-          command: |
-            git config user.email "core+streamlitbot-github@streamlit.io"
-            git config user.name "Streamlit Bot"
+          name: DEBUG Commit version updates
+          command: echo -e "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]"
 
-            git commit -am "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]" && git push origin release/$CIRCLE_TAG || echo "No changes to commit"
+      # - run:
+      #     name: Commit version updates
+      #     command: |
+      #       git config user.email "core+streamlitbot-github@streamlit.io"
+      #       git config user.name "Streamlit Bot"
+
+      #       git commit -am "Up version to $STREAMLIT_RELEASE_VERSION [skip ci]" && git push origin release/$CIRCLE_TAG || echo "No changes to commit"
 
       # Password added to circleci environment
       # https://ui.circleci.com/settings/project/github/streamlit/streamlit/environment-variables
-      - run:
-          name: init .pypirc
-          command: |
-            cd lib
-            echo -e "[pypi]" >> ~/.pypirc
-            echo -e "username = streamlit" >> ~/.pypirc
-            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
+      # - run:
+      #     name: init .pypirc
+      #     command: |
+      #       cd lib
+      #       echo -e "[pypi]" >> ~/.pypirc
+      #       echo -e "username = streamlit" >> ~/.pypirc
+      #       echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
 
       - run:
           name: Make package
@@ -419,10 +423,10 @@ jobs:
       - store_artifacts:
           path: ./lib/dist
 
-      - run:
-          name: Upload to pypi
-          command: |
-            make distribute
+      # - run:
+      #     name: Upload to pypi
+      #     command: |
+      #       make distribute
 
       - run:
           name: Create GitHub Release and merge PR
@@ -431,9 +435,9 @@ jobs:
             gh release create $CIRCLE_TAG -n "" -t $CIRCLE_TAG
             gh pr merge $GH_PR_NUMBER -m
 
-      - slack/status:
-          success_message: ":rocket: Version ${STREAMLIT_RELEASE_VERSION} was successful!"
-          failure_message: ":blobonfire: Version ${STREAMLIT_RELEASE_VERSION} failed to release"
+      # - slack/status:
+      #     success_message: ":rocket: Version ${STREAMLIT_RELEASE_VERSION} was successful!"
+      #     failure_message: ":blobonfire: Version ${STREAMLIT_RELEASE_VERSION} failed to release"
 
   python-max-version: &job-template
     docker:
